"""modelos gatos

Revision ID: 0e701692e806
Revises: 
Create Date: 2026-03-05 19:10:52.343420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e701692e806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('razas_gatos')
    op.alter_column('imagenes', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.create_index('idx_imagen_raza_fecha', 'imagenes', ['raza_id', 'fecha_extraccion'], unique=False)
    op.drop_constraint(op.f('imagenes_raza_id_fkey'), 'imagenes', type_='foreignkey')
    op.create_foreign_key(None, 'imagenes', 'razas', ['raza_id'], ['id'])
    op.add_column('metricas_etl', sa.Column('mensaje', sa.String(length=500), nullable=True))
    op.alter_column('metricas_etl', 'fecha_ejecucion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('metricas_etl', 'registros_extraidos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metricas_etl', 'registros_guardados',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metricas_etl', 'tiempo_ejecucion_segundos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('metricas_etl', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.drop_column('metricas_etl', 'mensaje_error')
    op.alter_column('razas', 'vida_promedio',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('razas', 'peso_metrico',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('razas', 'wikipedia_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('razas', 'wikipedia_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('razas', 'peso_metrico',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('razas', 'vida_promedio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('metricas_etl', sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.alter_column('metricas_etl', 'estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('metricas_etl', 'tiempo_ejecucion_segundos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metricas_etl', 'registros_guardados',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metricas_etl', 'registros_extraidos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metricas_etl', 'fecha_ejecucion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('metricas_etl', 'mensaje')
    op.drop_constraint(None, 'imagenes', type_='foreignkey')
    op.create_foreign_key(op.f('imagenes_raza_id_fkey'), 'imagenes', 'razas', ['raza_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_imagen_raza_fecha', table_name='imagenes')
    op.alter_column('imagenes', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('razas_gatos',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ancho', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('alto', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nombre_raza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origen_raza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vida_promedio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('peso_metrico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wikipedia_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_extraccion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
