DB_HOST = 'localhost'
DB_PORT = '5432'
DB_USER = 'postgres'
DB_PASSWORD = 'tu_contraseña'
DB_NAME = 'gatos_db'
DATABASE_URL = "postgresql://neondb_owner:npg_N1j6VbzJiUnI@ep-solitary-snow-aiy6lkoq-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"
